os: linux
dist: xenial
language: python
python:
  - "3.8"
  - "3.9"
install:
  - pip install -r test/requirements.txt
  - pip install -r requirements.txt
  - pip install codecov
script:
  - python -m unittest discover -v
after_success:
  - bash <(curl -s https://codecov.io/bash)
